"""Command-line entry point: python -m lefilter {extract,stats,build,leveling,ui}."""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tomllib
from datetime import datetime
from pathlib import Path

from . import filterxml
from .extract import DATA_VERSION, ExtractError, extract
from .filterxml import (BaseFilter, FilterHeader, assemble, insert_above_section, merge, read_filter, render_rule,
                        write_filter)
from .game import DATA_FOLDER, GameNotFound, find_filters_dir, find_game
from .paths import (CACHE_DIR, CONFIG_FILE, DATA_DIR, FROZEN, OUT_DIR, TEMPLATE_FILE, USER_DIR, prepare_user_dir,
                    save_game_dir, saved_game_dir)
from .leveling import LevelingPlan, parse_options, plan_leveling
from .sections import RuleInfo, place
from .starter import ensure_template
from .report import build_report, histogram_markdown, leveling_markdown
from .rules import ConfigError, Rule, RuleSpec, plan_affix_rules, plan_class_hide, plan_rules
from .tools import ToolError

DATA_FILE = DATA_DIR / "uniques.json"
MARKER_RE = re.compile(r"\s*\[auto-uniques[^\]]*\]")


def _load_data() -> dict:
    if not DATA_FILE.is_file():
        sys.exit(f"{DATA_FILE} missing - run `python -m lefilter extract` first")
    return json.loads(DATA_FILE.read_text(encoding="utf-8"))


def _ask_game_dir() -> Path | None:
    """Packaged app started by double-click: let the user paste the game folder."""
    if not (FROZEN and sys.stdin and sys.stdin.isatty()):
        return None
    print("\nLast Epoch wasn't found automatically. In Steam: right-click Last Epoch -> Manage -> "
          "Browse local files, then copy that folder's path from the address bar.")
    while True:
        text = input("Paste the Last Epoch folder here (or press Enter to quit): ").strip().strip('"')
        if not text:
            return None
        if (Path(text) / DATA_FOLDER).is_dir():
            return Path(text)
        print(f"That folder has no '{DATA_FOLDER}' folder in it - try again.")


def _find_game(args):
    """The game install: --game-dir, the folder remembered from last time, Steam's libraries,
    or (packaged app) the folder the user pastes. Aborts when there's none."""
    saved = saved_game_dir()
    for given in (args.game_dir, saved):
        if given:
            try:
                game = find_game(given)
            except GameNotFound:
                if given is args.game_dir:
                    raise
                continue
            if given != saved:
                save_game_dir(game.root)
            return game
    try:
        return find_game()
    except GameNotFound:
        pasted = _ask_game_dir()
        if not pasted:
            raise
        game = find_game(pasted)
        save_game_dir(game.root)
        return game


def _extract(args) -> dict:
    game = _find_game(args)
    print(f"Game: {game.root}  (build {game.short_hash}, Steam build {game.steam_build})")
    data = extract(game, CACHE_DIR, DATA_FILE, regen_schema=getattr(args, "regen_schema", False))
    print(f"Extracted {len(data['uniques'])} uniques for game version {data['game_version']} -> {DATA_FILE}")
    for w in data["warnings"]:
        print(f"  warning: {w}")
    return data


def _data_for_build(args) -> dict:
    """Current data, re-extracting first if the installed game build changed."""
    if args.no_extract:
        return _load_data()
    try:
        game = _find_game(args)
    except GameNotFound as e:
        if DATA_FILE.is_file():
            print(f"{e}\nUsing existing {DATA_FILE.name}.")
            return _load_data()
        raise
    if DATA_FILE.is_file():
        data = _load_data()
        if data["build_hash"] == game.build_hash and data.get("data_version") == DATA_VERSION:
            return data
        if data["build_hash"] != game.build_hash:
            print(f"Game build changed ({data['build_hash'][:12]} -> {game.short_hash}); re-extracting.")
        else:
            print("Data file is from an older version of this tool; re-extracting.")
    return _extract(args)


def _safe_name(name: str) -> str:
    return re.sub(r'[<>:"/\\|?*]', "_", name).strip()


def _write_checked(path: Path, text: str, force: bool) -> None:
    """Write a filter, refusing to clobber files this tool didn't generate (unless forced)."""
    if path.exists():
        existing = path.read_bytes().decode("utf-8-sig", errors="replace")
        if "[auto-uniques" not in existing and not force:
            sys.exit(f"{path} exists and was not generated by this tool; use --force to overwrite it")
        if not path.resolve().is_relative_to(OUT_DIR):
            backup = CACHE_DIR / "backups" / f"{path.stem}-{datetime.now():%Y%m%d-%H%M%S}.xml"
            backup.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, backup)
            print(f"Backed up previous {path.name} -> {backup}")
    write_filter(path, text)


def _resolve_base(base_ref: str, config: dict, data: dict) -> Path:
    """`base` as given, relative to the project, or in the game's Filters folder. The new-filter
    template is generated when it's the one asked for and doesn't exist yet."""
    filters_dir = find_filters_dir()
    candidates = [Path(base_ref), USER_DIR / base_ref] + ([filters_dir / base_ref] if filters_dir else [])
    for c in candidates:
        if c.is_file():
            return c
    if (USER_DIR / base_ref).resolve() == TEMPLATE_FILE.resolve():
        ensure_template(TEMPLATE_FILE, config, data)
        print(f"Generated the new-filter template {TEMPLATE_FILE}")
        return TEMPLATE_FILE
    sys.exit("base filter not found; tried:\n  " + "\n  ".join(str(c) for c in candidates))


def _block_info(block: str) -> RuleInfo:
    conditionless = "<Condition " not in block
    return RuleInfo(name=BaseFilter.rule_name(block), separator=conditionless,
                    catch_all=conditionless and "<isEnabled>true</isEnabled>" in block and "<type>HIDE</type>" in block)


def _leveling(config: dict, data: dict, only_enabled: bool = True) -> tuple[LevelingPlan, str] | None:
    """The [leveling] section's plan and rule prefix (None while it isn't enabled)."""
    table = config.get("leveling", {})
    if only_enabled and not table.get("enabled"):
        return None
    opts = parse_options(table, data["bases"])
    return plan_leveling(opts, data), opts.rule_prefix


def cmd_extract(args) -> None:
    _extract(args)


def cmd_stats(args) -> None:
    data = _load_data()
    config = tomllib.loads(Path(args.config).read_text(encoding="utf-8"))
    thresholds = {k: float(v) for k, v in config["rarity"].items()}
    print(f"Game version {data['game_version']}, {len(data['uniques'])} uniques\n")
    print(histogram_markdown(data["uniques"], thresholds))


def cmd_build(args) -> None:
    config = tomllib.loads(Path(args.config).read_text(encoding="utf-8"))
    data = _data_for_build(args)
    plan = plan_rules(config, data["uniques"])
    fcfg, mcfg = config.get("filter", {}), config.get("template", {})
    prefix = fcfg.get("rule_prefix", "")
    marker = f"[auto-uniques {data['game_version']} {data['build_hash'][:8]}]"
    generated = [render_rule(r) for r in plan.rules]
    affix_rules, affix_members, affix_warnings = plan_affix_rules(config, data["affixes"])
    plan.warnings += affix_warnings
    top = [render_rule(r) for r in affix_rules]
    class_rules = plan_class_hide(config)
    class_blocks = [render_rule(r) for r in class_rules]
    leveling = _leveling(config, data)

    base_ref = "" if args.standalone else (args.base or mcfg.get("base", ""))
    merge_info = None
    if base_ref:
        base_path = _resolve_base(base_ref, config, data)
        base = read_filter(base_path)
        result = merge(base, generated, prefix, mcfg.get("drop", []), mcfg.get("after", ""),
                       mcfg.get("keep_above", []), mcfg.get("keep"), top, class_blocks)
        name = args.name or mcfg.get("name") or f"{base.header.name} (auto)"
        header = FilterHeader(name=name, icon=base.header.icon, icon_color=base.header.icon_color,
                              description=(MARKER_RE.sub("", base.header.description) + " " + marker).strip(),
                              version=data["game_version"] or base.header.version)
        kept_names = [BaseFilter.rule_name(b) for b in result.blocks if b not in generated and b not in top]
        # Class hide rules close the section before the generated block's (in the template: after the exalted rules).
        blocks, _ = insert_above_section(result.blocks, result.insert_at, class_blocks)
        merge_info = (f"Built from `{base_path.name}`: kept {len(kept_names)} of its rules, "
                      f"replaced {len(result.removed)}, left out {len(result.left_out)}; "
                      f"generated block starts at position {result.insert_at + len(class_blocks) + 1} from the top.")
        merge_info += "\n\nKept from the base filter:\n\n" + "\n".join(f"- {n or '(unnamed)'}" for n in kept_names)
        if result.moved_above:
            merge_info += "\n\nKept above the generated block:\n\n" + "\n".join(f"- {n}" for n in result.moved_above)
        if result.removed:
            merge_info += "\n\nRemoved rules:\n\n" + "\n".join(f"- {n}" for n in result.removed)
    else:
        name = args.name or fcfg.get("name", "Uniques (auto)")
        header = FilterHeader(name=name, icon=fcfg.get("icon", 0), icon_color=fcfg.get("icon_color", 0),
                              description=(fcfg.get("description", "") + " " + marker).strip(),
                              version=data["game_version"] or "1.0")
        blocks = top + class_blocks + generated
        if fcfg.get("hide_other_uniques", True):
            catch_all = Rule(name=f"{prefix}Hide all other uniques and sets", group="", spec=RuleSpec(action="hide"),
                             unique_ids=None, rarity="UNIQUE SET")
            blocks.append(render_rule(catch_all))

    if leveling:
        lev_plan, lev_prefix = leveling
        plan.warnings += [f"leveling: {w}" for w in lev_plan.warnings]
        blocks, replaced, at = place(blocks, [_block_info(b) for b in blocks],
                                     [render_rule(r) for r in lev_plan.rules], lev_prefix)
        lev_info = (f"{len(lev_plan.rules)} rules at position {at + 1} from the top"
                    + (f", replacing {replaced} previous ones" if replaced else ""))

    text = assemble(header, blocks)
    out_xml = Path(args.out) if args.out else OUT_DIR / f"{_safe_name(name)}.xml"
    _write_checked(out_xml, text, args.force)
    report = OUT_DIR / f"{_safe_name(name)}.md"
    report.write_text(build_report(data, config, plan, name, len(blocks), merge_info, affix_rules, affix_members,
                                   leveling[0] if leveling else None, class_rules), encoding="utf-8")

    n_leveling = len(leveling[0].rules) if leveling else 0
    print(f"\n{len(plan.rules) + len(affix_rules) + len(class_rules) + n_leveling} generated rules, "
          f"{len(blocks)}/{filterxml.MAX_RULES} rules in '{name}'")
    for r in affix_rules:
        print(f"  {r.name:<36} {len(r.affix_ids):>4} affixes (top of the filter)")
    if class_rules:
        on = [r.name for r in class_rules if r.spec.enabled]
        print(f"  class hide rules: {len(class_rules)}, " + (f"enabled: {', '.join(on)}" if on else "all disabled"))
    for group, members in plan.members.items():
        print(f"  {group:<32} {len(members):>4} items")
    if leveling:
        print(f"  leveling section: {lev_info}")
    if merge_info:
        print(merge_info.split("\n")[0])
    for w in plan.warnings:
        print(f"  warning: {w}")
    print(f"Filter: {out_xml}\nReport: {report}")

    if args.install:
        filters_dir = find_filters_dir()
        if not filters_dir:
            sys.exit("Game filter folder not found; copy the file manually")
        target = filters_dir / out_xml.name
        _write_checked(target, text, args.force)
        print(f"Installed: {target}")


def cmd_leveling(args) -> None:
    config = tomllib.loads(Path(args.config).read_text(encoding="utf-8"))
    data = _load_data()
    if "bases" not in data:
        sys.exit(f"{DATA_FILE.name} predates base-item data - run `python -m lefilter extract` first")
    lev_plan, _ = _leveling(config, data, only_enabled=False)
    print(leveling_markdown(lev_plan, data))
    if not config.get("leveling", {}).get("enabled"):
        print("\n([leveling] enabled = false: `build` leaves this section out)")


def cmd_ui(args) -> None:
    from .ui import Api, serve
    tomllib.loads(Path(args.config).read_text(encoding="utf-8"))   # fail early on a broken config
    data = _data_for_build(args)
    serve(Api(data, Path(args.config), OUT_DIR, CACHE_DIR / "backups", TEMPLATE_FILE, DATA_DIR / "filter_icons",
              DATA_DIR / "lang"), args.port, not args.no_browser)


def cmd_selftest(args) -> None:
    """Load every component extraction needs (the release build runs this to catch missing pieces).
    TypeTreeGeneratorAPI isn't part of the packaged app: it's fetched on first use (tools.py)."""
    import importlib
    import platform
    from . import extract, tools  # noqa: F401  (UnityPy, with FMOD stubbed out)
    for module in ("UnityPy.export.Texture2DConverter", "UnityPy.export.SpriteHelper", "texture2ddecoder", "etcpak",
                   "astc_encoder", "ctypes", "zipfile", "ssl", "lefilter.ui"):
        importlib.import_module(module)
    if (platform.system(), platform.machine().lower()) not in tools.TTG_WHEELS:
        sys.exit(f"no TypeTreeGeneratorAPI build known for {platform.system()} {platform.machine()}")
    if platform.system() not in tools.CPP2IL_ASSETS:
        sys.exit(f"no Cpp2IL build known for {platform.system()}")
    tools.ssl_context()
    from .ui import WEB_DIR
    missing = [f for f in ("index.html", "app.js", "app.css") if not (WEB_DIR / f).is_file()]
    if missing:
        sys.exit(f"web files missing: {missing}")
    print("selftest ok")


def main(argv=None) -> None:
    p = argparse.ArgumentParser(prog="lefilter", description="Generate Last Epoch loot-filter rules for uniques from game data.")
    p.add_argument("--game-dir", type=Path, help="Last Epoch install folder (auto-detected from Steam otherwise)")
    p.add_argument("--config", default=str(CONFIG_FILE))
    sub = p.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("extract", help="read unique-item data from the installed game")
    e.add_argument("--regen-schema", action="store_true", help="rebuild the UniqueList schema with Cpp2IL")
    e.set_defaults(func=cmd_extract)

    s = sub.add_parser("stats", help="show unique counts per category and LPL range")
    s.set_defaults(func=cmd_stats)

    b = sub.add_parser("build", help="generate the filter XML (re-extracts automatically after a game patch)")
    b.add_argument("--standalone", action="store_true", help="ignore [template] and build a uniques/sets-only filter")
    b.add_argument("--base", help="base filter for the template (overrides [template].base)")
    b.add_argument("--name", help="filter name shown in game")
    b.add_argument("--out", help="output XML path (default: out/<name>.xml)")
    b.add_argument("--install", action="store_true", help="also write the filter into the game's Filters folder")
    b.add_argument("--force", action="store_true", help="overwrite filters not created by this tool")
    b.add_argument("--no-extract", action="store_true", help="use data/uniques.json as-is")
    b.set_defaults(func=cmd_build)

    lv = sub.add_parser("leveling", help="show the rules the [leveling] config section generates")
    lv.set_defaults(func=cmd_leveling)

    u = sub.add_parser("ui", help="open the filter editor / leveling generator in the browser")
    u.add_argument("--port", type=int, default=8765, help="port on 127.0.0.1 (0 = any free port)")
    u.add_argument("--no-browser", action="store_true", help="don't open a browser window")
    u.add_argument("--no-extract", action="store_true", help="use data/uniques.json as-is")
    u.set_defaults(func=cmd_ui)

    t = sub.add_parser("selftest", help="check that the program's components load")
    t.set_defaults(func=cmd_selftest)

    args = p.parse_args(argv)
    if args.cmd != "selftest":
        prepare_user_dir()
    try:
        args.func(args)
    except (ConfigError, ExtractError, GameNotFound, ToolError, ValueError) as e:
        sys.exit(f"error: {e}")


if __name__ == "__main__":
    main()
